### ISSUE TITLE
RemoteFileSystemServerConnector cannot be stopped

### ISSUE THREAD

**Issue by MalshaL** [wso2-ballerina/module-smb#2]
**Description:**
[RemoteFileSystemServerConnectorImpl](https://github.com/wso2/transport-file/blob/master/components/org.wso2.transport.remote-file-system/src/main/java/org/wso2/transport/remotefilesystem/server/connector/contractimpl/RemoteFileSystemServerConnectorImpl.java#L33) which is used for SMB Listener, does not have any option to stop/close the server connector object at the moment.

**Suggested Labels:**
Priority/High

**Affected Product Version:**
wso2/smb:0.1.0

**Comment by anupama-pathirage** [comment]
Closing as we are no longer maintaining this code.
